__title__ = 'twisc'
__license__ = 'MIT'
__version__ = '0.1.0'
__author__ = 'pchchv'
__contact__ = 'ipchchv@gmail.com'
__url__ = 'https://github.com/pchchv/twisc'
__description__ = 'Simple and unlimited Twitter scraper: tweets, likes, retweets, followers, user info, images, etc.'
